env: flex
threadsafe: true
automatic_scaling:
 max_num_instances: 1
env_variables:
 MONGO_URL: 'mongodb://admin:Xbox4life@ds151963.mlab.com:51963/midlane-main'
 ROOT_URL: 'https://midlane-178716.appspot.com'
 METEOR_SETTINGS: '{}'
